# Generated by Django 5.1.4 on 2025-01-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('value', models.ImageField(upload_to='images/product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
