# Generated by Django 5.1.4 on 2025-01-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
        ('products', '0004_pictureattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='pictures.image'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='picture_attribute',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pictureattribute'),
        ),
        migrations.AlterField(
            model_name='pictureattribute',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.image'),
        ),
    ]
