# Generated by Django 5.1.4 on 2025-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_images_productsku_picture_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product'),
        ),
    ]
